const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  list: () => ipcRenderer.invoke('accounts:list'),
  add: () => ipcRenderer.invoke('accounts:add'),
  delete: (userId) => ipcRenderer.invoke('accounts:delete', userId),
  reorder: (orderedUserIds) => ipcRenderer.invoke('accounts:reorder', orderedUserIds),
  setNote: (userId, note) => ipcRenderer.invoke('accounts:setNote', userId, note),
  launch: (userId, options) => ipcRenderer.invoke('accounts:launch', userId, options),
  exportAccounts: (passphrase) => ipcRenderer.invoke('accounts:export', passphrase),
  importAccounts: (passphrase) => ipcRenderer.invoke('accounts:import', passphrase),
  loadConfig: () => ipcRenderer.invoke('config:load'),
  saveConfig: (payload) => ipcRenderer.invoke('config:save', payload),
  getPlatform: () => ipcRenderer.invoke('app:getPlatform'),
  checkClientInstalled: () => ipcRenderer.invoke('app:checkClientInstalled'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  getAutoLaunch: () => ipcRenderer.invoke('app:getAutoLaunch'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('app:setAutoLaunch', enabled),
  getPreference: (key) => ipcRenderer.invoke('app:getPreference', key),
  setPreference: (key, value) => ipcRenderer.invoke('app:setPreference', key, value),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  checkForUpdates: () => ipcRenderer.invoke('app:checkForUpdates'),
  getLogPath: () => ipcRenderer.invoke('app:getLogPath'),
  openLogFile: () => ipcRenderer.invoke('app:openLogFile'),
  getBackupInfo: () => ipcRenderer.invoke('backup:getInfo'),
  openBackupsFolder: () => ipcRenderer.invoke('backup:openFolder'),

  onPresenceUpdate: (cb) => ipcRenderer.on('presence:update', (_e, accounts) => cb(accounts)),

  onMenuGotoSettings: (cb) => ipcRenderer.on('menu:goto-settings', cb),
  onMenuAddAccount: (cb) => ipcRenderer.on('menu:add-account', cb),
  onMenuRefresh: (cb) => ipcRenderer.on('menu:refresh', cb),
  onMenuViewMode: (cb) => ipcRenderer.on('menu:view-mode', (_e, mode) => cb(mode)),

  listMacros: () => ipcRenderer.invoke('macros:list'),
  saveMacro: (macro) => ipcRenderer.invoke('macros:save', macro),
  deleteMacro: (id) => ipcRenderer.invoke('macros:delete', id),
  setMacroHotkey: (id, hotkey) => ipcRenderer.invoke('macros:setHotkey', id, hotkey),
  startMacroRecording: () => ipcRenderer.invoke('macros:recordStart'),
  stopMacroRecording: () => ipcRenderer.invoke('macros:recordStop'),
  playMacro: (id) => ipcRenderer.invoke('macros:play', id),
  stopMacroPlaying: () => ipcRenderer.invoke('macros:stopPlaying'),
  isMacroPlaying: () => ipcRenderer.invoke('macros:isPlaying'),
  getCursorPos: () => ipcRenderer.invoke('macros:getCursorPos'),
  testMacroAction: (action) => ipcRenderer.invoke('macros:testAction', action),
  getScreenSize: () => ipcRenderer.invoke('macros:getScreenSize'),
  pickPixel: () => ipcRenderer.invoke('macros:pickPixel'),
  getKeyNames: () => ipcRenderer.invoke('macros:getKeyNames'),
  panicReleaseMacros: () => ipcRenderer.invoke('macros:panicRelease'),
  exportMacro: (id) => ipcRenderer.invoke('macros:export', id),
  importMacro: () => ipcRenderer.invoke('macros:import'),
  onMacroProgress: (cb) => ipcRenderer.on('macro:progress', (_e, data) => cb(data)),
  onMacroPanicked: (cb) => ipcRenderer.on('macro:panicked', () => cb()),
  onMacroKillSwitchChanged: (cb) => ipcRenderer.on('macro:killSwitchChanged', (_e, disabled) => cb(disabled)),
  getDisplays: () => ipcRenderer.invoke('macros:getDisplays'),
  getKillSwitch: () => ipcRenderer.invoke('macros:getKillSwitch'),
  setKillSwitch: (disabled) => ipcRenderer.invoke('macros:setKillSwitch', disabled),
  getMacroVersions: (id) => ipcRenderer.invoke('macros:getVersions', id),
  restoreMacroVersion: (id, versionAt) => ipcRenderer.invoke('macros:restoreVersion', id, versionAt),
  playMacroFrom: (id, startIndex) => ipcRenderer.invoke('macros:playFrom', id, startIndex),
  validateMacro: (macro) => ipcRenderer.invoke('macros:validate', macro),
  bulkDeleteMacros: (ids) => ipcRenderer.invoke('macros:bulkDelete', ids),
  bulkAddMacroTag: (ids, tag) => ipcRenderer.invoke('macros:bulkAddTag', ids, tag),
  getSessionInfo: () => ipcRenderer.invoke('app:getSessionInfo'),
  setLaunchMacro: (userId, macroId) => ipcRenderer.invoke('accounts:setLaunchMacro', userId, macroId),

  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  zoomIn: () => ipcRenderer.invoke('window:zoomIn'),
  zoomOut: () => ipcRenderer.invoke('window:zoomOut'),
  resetZoom: () => ipcRenderer.invoke('window:resetZoom'),
  toggleFullscreen: () => ipcRenderer.invoke('window:toggleFullscreen'),
  quitApp: () => ipcRenderer.invoke('app:quit'),
  showAbout: () => ipcRenderer.invoke('app:showAbout'),
});
